/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * StringList.java
 *
 * Created on Aug 17, 2009, 7:59:10 PM
 */

package demolist2;

import java.lang.Integer;
import java.util.ArrayList;
import javax.swing.JList;
import javax.swing.event.ListDataEvent;
import javax.swing.event.ListDataListener;

/**
 *
 * @author tunn
 */
public class ListModelDemo extends javax.swing.JFrame {
    private String[] data=new String[]{"A","B","C"};
    private ArrayList<Student> mydata=new ArrayList<Student>();
    StudentListModel model;
    /** Creates new form StringList */
    public ListModelDemo() {
        model=new StudentListModel(mydata);
        model.addStudent(new Student("Nguyen Van A",18));
        model.addStudent(new Student("Nguyen Thi B",20));
        model.addStudent(new Student("Pham Van C",5));
        
        initComponents();
        
        
        model.addListDataListener(new ListDataListener(){

            public void intervalAdded(ListDataEvent e) {
                ///throw new UnsupportedOperationException("Not supported yet.");
                System.out.println("Add");

            }

            public void intervalRemoved(ListDataEvent e) {
                ///throw new UnsupportedOperationException("Not supported yet.");
                System.out.println("Remove");
            }

            public void contentsChanged(ListDataEvent e) {
                //throw new UnsupportedOperationException("Not supported yet.");
                System.out.println("Update");
            }

        });

        
        

        //listView.setModel(model);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listView = new JList(model);
        jButton1 = new javax.swing.JButton();
        txtContent = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        listView.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                listViewValueChanged(evt);
            }
        });
        jScrollPane1.setViewportView(listView);

        jButton1.setText("Add");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        txtContent.setText("jTextField1");

        txtAge.setText("jTextField1");

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtAge, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete))
                    .addComponent(txtContent, javax.swing.GroupLayout.DEFAULT_SIZE, 376, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtContent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAge, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Student std=new Student(txtContent.getText(),Integer.parseInt(txtAge.getText()));
        //mydata.add(std);
        model.addStudent(std);
        listView.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void listViewValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_listViewValueChanged
        // TODO add your handling code here:
        //System.out.println(evt.getSource());
        Student std=(Student) listView.getSelectedValue();

        txtContent.setText(std.getName());
        txtAge.setText(Integer.toString(std.getAge()));

    }//GEN-LAST:event_listViewValueChanged

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        Student std=(Student) listView.getSelectedValue();

        std.setName(txtContent.getText());
        std.setAge(Integer.parseInt(txtAge.getText()));
        
        model.updateStudent(std, listView.getSelectedIndex());
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        Student std=(Student) listView.getSelectedValue();
        model.removeStudent(std);
    }//GEN-LAST:event_btnDeleteActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ListModelDemo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList listView;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtContent;
    // End of variables declaration//GEN-END:variables

}
